### ISSUE TITLE
Deploy on AWS Cloud Provider

### ISSUE THREAD

**Issue by jsenon** [retroryan/istio-workshop#13]
Hi, 
I propose to have a section for deployment of this workshop on AWS Cloud Provider. Before starting to document it, what's your feeling about that?
Regards

**Comment by retroryan** [comment]
Hello!  - That is a great idea.   It would be great to have this supported on multiple clouds.   Are you thinking of adding a version of exercise 1 setup specifically for AWS?  And then there could eventually be an Exercise 1 for different cloud providers?

Thank you for contributing!

**Comment by jsenon** [comment]
Yes, have exercice 1 for AWS, and why not added other cloud provider, but I don't know very well the other one.

**Comment by retroryan** [comment]
That would be great if you added just AWS.  I can see if we can get someone from IBM to add bluemix, etc.

**Comment by jsenon** [comment]
Make sense. I will document how to deploy with kops, who is for me a quick way to deploy basic cluster for a workshop

**Comment by retroryan** [comment]
Thanks to @jsenon  - this is now completed!
