### ISSUE TITLE
route-rule-80-20 precedence needs to be higher than helloworld-default routerule

### ISSUE THREAD

**Issue by Cuneytt** [retroryan/istio-workshop#30]
in [Request Routing and Canary Testing](https://github.com/retroryan/istio-workshop/blob/master/exercise-10/README.md#exercise-10---request-routing-and-canary-testing) it is mentioned that "This can be done by creating another rule with a higher precedence that routes some of the traffic to v2" but the precedence is still 1 causing this routerule to be ignored.

**Comment by craigbox** [comment]
Updates to the workshop for the v1alpha3 API have fixed this.  (Precedence and RouteRules have been removed in favour of VirtualServices.)

/close
