### ISSUE TITLE
perTryTimeout invalid:  duration: nil Duration

### ISSUE THREAD

**Issue by esnible** [retroryan/istio-workshop#32]
There is a problem with a route rule.  Tested with Istio 0.8.

$ istioctl create -f route-rule-retry.yaml 
Error: configuration is invalid: 1 error occurred:

* perTryTimeout invalid:  duration: nil Duration

**Comment by retroryan** [comment]
@saturnism  - Do you have any ideas what would have changed with Istio 0.8 to break this?

**Comment by esnible** [comment]
Perhaps it is this change from four months ago:

https://github.com/istio/istio/blame/master/pilot/pkg/model/validation.go#L1285

```
if dur < time.Millisecond {
@GregHanson
@kyessenov
changed from double to duration (#614)
a year ago
1286
		return errors.New("duration must be greater than 1ms")
1287
	}
```

**Comment by retroryan** [comment]
This should be fixed with the latest versions of istio.
