### ISSUE TITLE
Missing 'istio/guestbook-ui-vs.yaml'

### ISSUE THREAD

**Issue by Klazomenai** [retroryan/istio-workshop#42]
`istio/guestbook-ui-vs.yaml` appears to be missing from all the sources provided and this repo. 

Reference: Exercise 7, [Step 2 - Create a Virtual Service](https://github.com/retroryan/istio-workshop/blob/master/exercise-7/README.md#configure-guestbook-ingress)

**Comment by retroryan** [comment]
Fixed with updates to Istio 1.0.2
