### ISSUE TITLE
Workaround for Istio issue #10062

### ISSUE THREAD

**Issue by oletizi** [retroryan/istio-workshop#48]
Recent versions of Istio (1.0.3?,  1.0.4, 1.0.5, 1.1.0-snapshot.3) have an issue which prevents guestbook-service connections to mysql:

[https://github.com/istio/istio/issues/10062](https://github.com/istio/istio/issues/10062)

There's a workaround in the discussion that fixed the issue for me:

`kubectl delete meshpolicies.authentication.istio.io default`

It might be worth adding a note about this workaround--at least until the issue is fixed. I spent quite a while poking around trying to figure out what was wrong. While that was a useful exercise, it might save others some time.

**Comment by retroryan** [comment]
Thank you for the suggestion, I agree this would be useful.  Would you mind opening a PR with the note?

**Comment by oletizi** [comment]
Sure thing.
